#Xpress Insight User Admin Cli
#============================
#correctPasswordPromptTest.sh
#```````````````````````
#Command line tool to perform user management operations for Xpress Insight 4.x
#(c) Copyright 2019 Fair Isaac Corporation

#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

#!/usr/bin/expect -f
spawn java -jar ../../../target/insightadmincli.jar user list -u admin -url https://insight4-pgsql.svc.xpressdev.useast1-fws.ficoanalyticcloud.com
expect "Enter the password:" {send "admin123\r"}
expect {
"**** USER LIST OPERATION END *****" {send_user "\nOPERATION END FOUND!!\nSUCCESS TESTCASE\n"}

"Invalid credentials. Process finished with exit code 1" {send_user "\nWRONG PASSWORD!! \nFAILURE TESTCASE\n"}

"Password is mandatory. Process finished with exit code 1" {send_user "\nEMPTY PASSWORD!! \nFAILURE TESTCASE\n"}
}
